---
title: "SankeyFunctions"
author: "Ikehara"
date: '2022-04-30'
output: html_document
---

```{r setup, include=FALSE}
####################BEGIN FUNCTION####################################
library(networkD3)
sankplot <- function(Sakdata){
  
  # I need a long format
  sankdata_long <- Sakdata %>%
    rownames_to_column %>%
    gather(key = 'key', value = 'value', -rowname) #%>%
    #filter(value > 0)
  colnames(sankdata_long) <- c("source", "target", "value")
  
  sankdata_long$target <- paste(sankdata_long$target, " ", sep="")
  
    # From these flows we need to create a node data frame: it lists every entities involved in the flow
  nodes <- data.frame(name=c(as.character(sankdata_long$source), as.character(sankdata_long$target)) %>% unique())
   
    # With networkD3, connection must be provided using id, not using real name like in the links dataframe.. So we need to reformat it.
  sankdata_long$IDsource=match(sankdata_long$source, nodes$name)-1 
  sankdata_long$IDtarget=match(sankdata_long$target, nodes$name)-1
  
    # prepare colour scale
  ColourScal ='d3.scaleOrdinal() .range(["#FDE725FF","#B4DE2CFF","#6DCD59FF","#35B779FF","#1F9E89FF","#26828EFF","#31688EFF","#3E4A89FF","#482878FF","#440154FF"])'
  
    # Make the Network
  p <- sankeyNetwork(Links = sankdata_long, Nodes = nodes,
                    Source = "IDsource", Target = "IDtarget",
                    Value = "value", NodeID = "name", 
                    sinksRight=FALSE, colourScale=ColourScal, nodeWidth=40, fontSize=13, nodePadding=20)
  sankeyNetworkOutput(p)
  return(p)
}
###################END FUNCTION#######################################
```


```{r setup, include=FALSE}
#Load data
GFdata <- read.table("/Users/adam/Desktop/GFSank.csv", row.names = 1, header=TRUE, sep = ",", stringsAsFactors=TRUE)
GEdata <- read.table("/Users/adam/Desktop/GESank.csv", row.names = 1, header=TRUE, sep = ",", stringsAsFactors=TRUE)
GWdata <- read.table("/Users/adam/Desktop/GWSank.csv", row.names = 1, header=TRUE, sep = ",", stringsAsFactors=TRUE)
FEdata <- read.table("/Users/adam/Desktop/FESank.csv", row.names = 1, header=TRUE, sep = ",", stringsAsFactors=TRUE)
FWdata <- read.table("/Users/adam/Desktop/FWSank.csv", row.names = 1, header=TRUE, sep = ",", stringsAsFactors=TRUE)
WEdata <- read.table("/Users/adam/Desktop/WESank.csv", row.names = 1, header=TRUE, sep = ",", stringsAsFactors=TRUE)


##type into terminal to return sankey plots!!!
#sankplot(GFdata)
#sankplot(GEdata)
#sankplot(GWdata)
#sankplot(FEdata)
#sankplot(FWdata)
#sankplot(WEdata)

```